# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Continuous integration

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install aiohttp flake8 mypy
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 aionanoleaf --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 aionanoleaf --count --max-complexity=20 --max-line-length=150 --statistics
    - name: Test with mypy 
      run: |
        mypy aionanoleaf
